dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: mysql
  version: 1.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
