dependencies:
- name: cargocms-admin-client
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- condition: mysql.enabled
  name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.3.1
